export const GET_AMBASSADOR = "GET_AMBASSADOR"
export const GET_ERRORS = "GET_ERRORS"
export const GET_STARTLOADING = "GET_STARTLOADING"
export const GET_STOPLOADING ="GET_STOPLOADING"

export const GET_GUARANTOR = "GET_GUARANTOR"

export const REGISTER_SUCCESS ="REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"
export const CLEAR_PROFILE = "CLEAR_PROFILE"


export const SUCCESS = "ALERT_SUCCESS"
export const ERROR = "ALERT_ERROR"