export const REGISTER_SUCCESS ="REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"
export const CLEAR_PROFILE = "CLEAR_PROFILE"
//Ambassadors
export const GET_AMBASSADOR = "GET_AMBASSADOR"
export const GET_ERRORS = "GET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const GET_STARTLOADING = "GET_STARTLOADING"
export const GET_STOPLOADING ="GET_STOPLOADING"

export const GET_GUARANTOR = "GET_GUARANTOR"
//Employees
export const GET_EMPLOYEES = "GET_EMPLOYEES"
export const POST_EMPLOYEES = "POST_EMPLOYEES"
export const UPDATE_EMPLOYEES= "UPDATE_EMPLOYEES"
export const DELETE_EMPLOYEES = "DELETE_EMPLOYEES"
//Client
export const GET_CLIENT = "GET_CLIENT"
export const POST_CLIENT = "POST_CLIENT"
export const UPDATE_CLIENT = "UPDATE_CLIENT"
export const DELETE_CLIENT = "DELETE_CLIENT"
// Salary
export const GET_SALARY = "GET_SALARY"
export const POST_SALARY = "POST_SALARY"
export const UPDATE_SALARY = "UPDATE_SALARY"
export const DELETE_SALARY = "DELETE_SALARY"

export const GET_LEAVE = "GET_LEAVE"




export const SUCCESS = "ALERT_SUCCESS"
export const ERROR = "ALERT_ERROR"
